spring:
  application:
    name: RechargePoc

server:
  port: 8080
  servlet:
    contextPath: /recharge/poc

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      jri:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 30
        minimumNumberOfCalls: 100
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED
      ss:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 30
        minimumNumberOfCalls: 100
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED
      payOne:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 30
        minimumNumberOfCalls: 100
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED


fallback:
  isRequired: true