spring:
  application:
    name: RechargePoc

server:
  port: 8080
  servlet:
    contextPath: /recharge/poc

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      jri:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 40 #TODO Product will confirm
        minimumNumberOfCalls: 50
        automaticTransitionFromOpenToHalfOpenEnabled: false
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 25
        slidingWindowType: COUNT_BASED
      ss:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 50
        automaticTransitionFromOpenToHalfOpenEnabled: false
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 20
        slidingWindowType: COUNT_BASED
      payOne:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 40
        minimumNumberOfCalls: 50
        automaticTransitionFromOpenToHalfOpenEnabled: false
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


fallback:
  isRequired: false