spring:
  application:
    name: RechargePoc

server:
  port: 8080
  servlet:
    contextPath: /recharge/poc

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      jri:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10 #TODO Explore this
        failureRateThreshold: 40 #TODO Product will confirm
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 100s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10 #TODO Explore this
        slidingWindowType: COUNT_BASED #TODO Explore this


#  retry:
#    instances:
#      ss:
#        maxRetryAttempts: 5
#        waitDuration: 10s
#      jri:
#        maxRetryAttempts: 5
#        waitDuration: 10s
#      payOne:
#        maxRetryAttempts: 5
#        waitDuration: 10s